---
- name: Executing remote shell script
  hosts: all
  tasks:
    - name: Copy serverinfo Script
      copy: src=/tmp/serverinfo.sh dest=/tmp/ mode=0755
    - name: Execute Remote Script file
      command: sh /tmp/serverinfo.sh
      register: version
    - name: Copy the file to Master Server
      command: scp /Inventory/*.txt 192.168.237.129:/Inventory/
...
