---
- name: Executing remote shell script
  hosts: all
  tasks:
    - name: Copy serverinfo Script
      copy: src=/tmp/serverinfo.sh dest=/tmp/ mode=0755
    - name: Execute Remote Script file
      command: sh /tmp/serverinfo.sh
      register: version
    - debug:
      var: version.stdout_lines
...
